export const env = "productioning";

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
 export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";
export const CREATE_NEW_USER_FAILURE= 'CREATE_NEW_USER_FAILURE';
export const CREATE_NEW_USER_REQUEST= 'CREATE_NEW_USER_REQUEST';
export const CREATE_NEW_USER_SUCCESS= 'CREATE_NEW_USER_SUCCESS';
export const GET_USER_DATA_FAILURE= 'GET_USER_DATA_FAILURE';
export const GET_USER_DATA_REQUEST= 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS= 'GET_USER_DATA_SUCCESS';
export const GET_CURRENT_USER_DATA_FAILURE= 'GET_CURRENT_USER_DATA_FAILURE';
export const GET_CURRENT_USER_DATA_REQUEST= 'GET_CURRENT_USER_DATA_REQUEST';
export const GET_CURRENT_USER_DATA_SUCCESS= 'GET_CURRENT_USER_DATA_SUCCESS';
export const SENT_EMAIL_VERIFICATION_REQUEST = "SENT_EMAIL_VERIFICATION_REQUEST";
export const SENT_EMAIL_VERIFICATION_SUCCESS = "SENT_EMAIL_VERIFICATION_SUCCESS";
export const SENT_EMAIL_VERIFICATION_FAILURE = "SENT_EMAIL_VERIFICATION_FAILURE";
export const SEND_PASSWORD_RESET_EMAIL_REQUEST = "SEND_PASSWORD_RESET_EMAIL_REQUEST";
export const SEND_PASSWORD_RESET_EMAIL_SUCCESS = "SEND_PASSWORD_RESET_EMAIL_SUCCESS";
export const SEND_PASSWORD_RESET_EMAIL_FAILURE = "SEND_PASSWORD_RESET_EMAIL_FAILURE";
export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAILURE = 'UPDATE_USER_DETAILS_FAILURE';

export const ERROR_CODE_ACCOUNT_EXISTS =
  'auth/account-exists-with-different-credential';

export const ERROR_MSG_ACCOUNT_EXISTS = `
  An account with an E-Mail address to
  this social account already exists. Try to login from
  this account instead and associate your social accounts on
  your personal account page.
`;
export const ERROR_CODE_ACCOUNT_ALREADY_EXISTS = 'auth/email-already-in-use';
export const ERROR_MSG_ACCOUNT_ALREADY_EXISTS = `
An account with an E-Mail address is already exists. Try to login from
  this account instead.`;
export const ERROR_CODE_WRONG_PASSWORD = 'auth/wrong-password';
export const ERROR_CODE_INVALID_CREDENTIALS = 'auth/invalid-credential';
export const ERROR_MSG_WRONG_PASSWORD = `Wrong Password! \n Please try again`;
export const ERROR_CODE_TOO_MANY_ATTEMPTS = "auth/too-many-requests";
export const ERROR_MSG_TOO_MANY_ATTEMPTS = `Access to this account has been temporarily disabled due to many failed 
login attempts.\n You can immediately restore it by resetting your password or you can try again later.`
export const ERROR_CODE_INVALID_LOGIN_CREDS = "auth/invalid-login-credentials";
export const ERROR_MSG_INVALID_LOGIN_CREDS = `Email or Password wrong.! \n Please try again`
export const ERROR_CODE_MISSING_LOGIN_CREDS = "auth/missing-password";
export const ERROR_MSG_MISSING_LOGIN_CREDS = `Password Missing.! \n Please try again`

// actionTypes.js
export const ADD_ROLE_REQUEST = "ADD_ROLE_REQUEST";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const ADD_ROLE_FAILURE = "ADD_ROLE_FAILURE";

export const REMOVE_ROLE_REQUEST = "REMOVE_ROLE_REQUEST";
export const REMOVE_ROLE_SUCCESS = "REMOVE_ROLE_SUCCESS";
export const REMOVE_ROLE_FAILURE = "REMOVE_ROLE_FAILURE";

// actions/types.js
export const ADD_PATIENT_REQUEST = 'ADD_PATIENT_REQUEST';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_FAILURE = 'ADD_PATIENT_FAILURE';

export const UPDATE_PATIENT_REQUEST = 'UPDATE_PATIENT_REQUEST';
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS';
export const UPDATE_PATIENT_FAILURE = 'UPDATE_PATIENT_FAILURE';

export const DELETE_PATIENT_REQUEST = 'DELETE_PATIENT_REQUEST';
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS';
export const DELETE_PATIENT_FAILURE = 'DELETE_PATIENT_FAILURE';

export const GET_PATIENTS_REQUEST = 'GET_PATIENTS_REQUEST';
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAILURE = 'GET_PATIENTS_FAILURE';

export const GET_UNASSIGNED_PATIENTS_REQUEST = 'GET_UNASSIGNED_PATIENTS_REQUEST';
export const GET_UNASSIGNED_PATIENTS_SUCCESS = 'GET_UNASSIGNED_PATIENTS_SUCCESS';
export const GET_UNASSIGNED_PATIENTS_FAILURE = 'GET_UNASSIGNED_PATIENTS_FAILURE';

export const GET_ASSIGNED_PATIENTS_REQUEST = "GET_ASSIGNED_PATIENTS_REQUEST";
export const GET_ASSIGNED_PATIENTS_SUCCESS = "GET_ASSIGNED_PATIENTS_SUCCESS";
export const GET_ASSIGNED_PATIENTS_FAILURE = "GET_ASSIGNED_PATIENTS_FAILURE";

// redux/caregiverActionTypes.js
export const ADD_CAREGIVER_REQUEST = 'ADD_CAREGIVER_REQUEST';
export const ADD_CAREGIVER_SUCCESS = 'ADD_CAREGIVER_SUCCESS';
export const ADD_CAREGIVER_FAILURE = 'ADD_CAREGIVER_FAILURE';

export const UPDATE_CAREGIVER_REQUEST = 'UPDATE_CAREGIVER_REQUEST';
export const UPDATE_CAREGIVER_SUCCESS = 'UPDATE_CAREGIVER_SUCCESS';
export const UPDATE_CAREGIVER_FAILURE = 'UPDATE_CAREGIVER_FAILURE';

export const DELETE_CAREGIVER_REQUEST = 'DELETE_CAREGIVER_REQUEST';
export const DELETE_CAREGIVER_SUCCESS = 'DELETE_CAREGIVER_SUCCESS';
export const DELETE_CAREGIVER_FAILURE = 'DELETE_CAREGIVER_FAILURE';

export const FETCH_CAREGIVERS_REQUEST = 'FETCH_CAREGIVERS_REQUEST';
export const FETCH_CAREGIVERS_SUCCESS = 'FETCH_CAREGIVERS_SUCCESS';
export const FETCH_CAREGIVERS_FAILURE = 'FETCH_CAREGIVERS_FAILURE';

export const FETCH_AVAILABLE_CAREGIVERS_REQUEST = 'FETCH_AVAILABLE_CAREGIVERS_REQUEST';
export const FETCH_AVAILABLE_CAREGIVERS_SUCCESS = 'FETCH_AVAILABLE_CAREGIVERS_SUCCESS';
export const FETCH_AVAILABLE_CAREGIVERS_FAILURE = 'FETCH_AVAILABLE_CAREGIVERS_FAILURE';
// caregiverTypes.js

export const ASSIGN_CAREGIVER_REQUEST = 'ASSIGN_CAREGIVER_REQUEST';
export const ASSIGN_CAREGIVER_SUCCESS = 'ASSIGN_CAREGIVER_SUCCESS';
export const ASSIGN_CAREGIVER_FAILURE = 'ASSIGN_CAREGIVER_FAILURE';

export const REMOVE_CAREGIVER_REQUEST = 'REMOVE_CAREGIVER_REQUEST';
export const REMOVE_CAREGIVER_SUCCESS = 'REMOVE_CAREGIVER_SUCCESS';
export const REMOVE_CAREGIVER_FAILURE = 'REMOVE_CAREGIVER_FAILURE';

export const FETCH_ASSIGNED_CAREGIVERS_REQUEST = 'FETCH_ASSIGNED_CAREGIVERS_REQUEST';
export const FETCH_ASSIGNED_CAREGIVERS_SUCCESS = 'FETCH_ASSIGNED_CAREGIVERS_SUCCESS';
export const FETCH_ASSIGNED_CAREGIVERS_FAILURE = 'FETCH_ASSIGNED_CAREGIVERS_FAILURE';
 // actionTypes.js
export const FETCH_CAREGIVER_DETAILS_REQUEST = 'FETCH_CAREGIVER_DETAILS_REQUEST';
export const FETCH_CAREGIVER_DETAILS_SUCCESS = 'FETCH_CAREGIVER_DETAILS_SUCCESS';
export const FETCH_CAREGIVER_DETAILS_FAILURE = 'FETCH_CAREGIVER_DETAILS_FAILURE';

// src/redux/appointments/types.js

export const FETCH_APPOINTMENTS_REQUEST = 'FETCH_APPOINTMENTS_REQUEST';
export const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS';
export const FETCH_APPOINTMENTS_FAILURE = 'FETCH_APPOINTMENTS_FAILURE';

export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE';

export const UPDATE_APPOINTMENT_REQUEST = 'UPDATE_APPOINTMENT_REQUEST';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';
export const UPDATE_APPOINTMENT_FAILURE = 'UPDATE_APPOINTMENT_FAILURE';

export const DELETE_APPOINTMENT_REQUEST = 'DELETE_APPOINTMENT_REQUEST';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_FAILURE = 'DELETE_APPOINTMENT_FAILURE';


// Notifications

// redux/types.js
export const NOTIFICATIONS_FETCH_REQUEST = 'NOTIFICATIONS_FETCH_REQUEST';
export const NOTIFICATIONS_FETCH_SUCCESS = 'NOTIFICATIONS_FETCH_SUCCESS';
export const NOTIFICATIONS_FETCH_FAILURE = 'NOTIFICATIONS_FETCH_FAILURE';
export const NEW_NOTIFICATION_RECEIVED = 'NEW_NOTIFICATION_RECEIVED';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
